#!/usr/bin/env python

import loadlib


# just dumbly copy some stuff
loadlib.copy(['CNAME', 'static/*'])


# load the blog posts
posts = []
for src_path, dirname, files in loadlib.each_dir('blog-posts'):

    copied_files = loadlib.copy(files, src=src_path,
                                dest='post-files/{}'.format(dirname))

    post_obj = {
        'slug': dirname,
        'body': loadlib.load_markdown('body.md', src=src_path),
        'files': copied_files,
    }

    meta = loadlib.load_json('meta.json', src=src_path)
    post_obj.update({
        'title': meta['title'],
        'published': meta['published'],
    })

    posts.append(post_obj)


loadlib.write_json(posts, 'posts.json')

